name: Pre-merge Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches-ignore: ["version-*"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-ci:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    if: ${{ !github.event.pull_request.draft && github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]' }}
    steps:
      # If the condition above is not met, aka, the PR is not in draft status, then this step is skipped.
      # Because this step is part of the critical path, omission of this step will result in remaining CI steps not gettinge executed.
      # As of 8/8/2022 there is now way to enforce this beahvior in GitHub Actions CI.
      - run: exit 0

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - run: npm ci

      - name: Build
        run: |
          npm run build
